"""
Django settings for django_backend project.

Generated by 'django-admin startproject' using Django 4.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

"""
Django Settings.py - Purpose and Relationship

Theoretical Understanding
The settings.py file serves as the central configuration file for a Django project. It controls project-wide 
settings including database connections, installed apps, middleware configuration, security settings, and 
various Django framework options.

Relationship with Other Components

1. Apps and Models
- Defines INSTALLED_APPS that Django should recognize
- Specifies custom user model with AUTH_USER_MODEL
- Controls database configurations that models use

2. Security and Authentication
- Manages security settings like SECRET_KEY
- Configures authentication backends
- Sets password validation rules

3. Middleware and URLs
- Defines middleware stack order
- Sets root URL configuration
- Controls CORS and other request/response modifications

Current Implementation
1. Core Settings
- Debug mode enabled for development
- Custom user model configured
- PostgreSQL database connection
- CORS configuration for frontend integration

2. Security Settings
- Development-focused configuration
- Password validation disabled for testing
- CORS allowed origins set for localhost

3. Application Configuration
- Django built-in apps
- REST Framework integration
- Custom core app
- CORS headers support

Central Django settings for the entire backend runtime.

This file answers the big environment questions a new backend developer usually
has first:

- Which apps are installed?
- Which database does the project use in development and in tests?
- Which authentication backends are enabled?
- Which frontend origins may call the API?

When the backend behaves differently between local runs and tests, this file is
usually the first place to inspect.
"""

from pathlib import Path
import sys

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'your-secret-key'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
}

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Third-party apps
    'rest_framework',
    'rest_framework.authtoken',
    'django_filters',
    'core',
    'planner',
    'commerce',
    'corsheaders',
]

# Custom user model
AUTH_USER_MODEL = 'core.User'

MIDDLEWARE = [
    # Add CORS middleware at the top
    'corsheaders.middleware.CorsMiddleware',

    # Django middleware
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'django_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'django_backend.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'songfei_db',
        'USER': 'songfei_user',
        'PASSWORD': '8129',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}

if 'test' in sys.argv:
    DATABASES['default'] = {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': ':memory:',
    }


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = []

# for use in production
"""
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]"""

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOCAL_FRONTEND_ORIGINS = [
    'http://localhost:3000',
    'http://127.0.0.1:3000',
    'http://localhost:3001',
    'http://127.0.0.1:3001',
]

CORS_ALLOWED_ORIGINS = LOCAL_FRONTEND_ORIGINS
CSRF_TRUSTED_ORIGINS = LOCAL_FRONTEND_ORIGINS

#CORS_ALLOW_ALL_ORIGINS = True