# Generated by Django 5.2.7 on 2026-03-06 15:12

import django.core.validators
import django.db.models.deletion
import planner.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0008_employee_is_active_employee_worker_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KitchenDesignerProductProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False)),
                ('catalog_state', models.CharField(choices=[('draft', 'Draft'), ('staging', 'Staging'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('planner_role', models.CharField(blank=True, choices=[('base', 'Base cabinet'), ('wall', 'Wall cabinet'), ('tall', 'Tall cabinet'), ('panel', 'Panel'), ('benchtop', 'Benchtop'), ('appliance', 'Appliance'), ('accessory', 'Accessory')], max_length=20)),
                ('glb_file', models.FileField(blank=True, null=True, upload_to=planner.models._profile_upload_path, validators=[django.core.validators.FileExtensionValidator(['glb'])])),
                ('width_mm', models.PositiveIntegerField(blank=True, null=True)),
                ('depth_mm', models.PositiveIntegerField(blank=True, null=True)),
                ('height_mm', models.PositiveIntegerField(blank=True, null=True)),
                ('bounding_box_mm', models.JSONField(blank=True, default=dict)),
                ('origin_anchor', models.CharField(choices=[('floor_back_left', 'Floor back left'), ('floor_back_center', 'Floor back center'), ('center', 'Center')], default='floor_back_left', max_length=30)),
                ('default_rotation_deg', models.IntegerField(default=0)),
                ('requires_wall_attachment', models.BooleanField(default=False)),
                ('requires_benchtop', models.BooleanField(default=False)),
                ('supports_left_end_panel', models.BooleanField(default=False)),
                ('supports_right_end_panel', models.BooleanField(default=False)),
                ('pricing_mode', models.CharField(choices=[('use_product_price', 'Use product price'), ('override', 'Override'), ('formula', 'Formula')], default='use_product_price', max_length=20)),
                ('override_price', models.FloatField(blank=True, null=True)),
                ('interaction_schema', models.JSONField(blank=True, default=dict)),
                ('constraint_schema', models.JSONField(blank=True, default=dict)),
                ('compatibility_schema', models.JSONField(blank=True, default=dict)),
                ('has_production_assets', models.BooleanField(default=False)),
                ('production_asset_notes', models.TextField(blank=True)),
                ('validation_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kitchen_designer_profile', to='core.product')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_kitchen_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['product__name'],
            },
        ),
        migrations.CreateModel(
            name='KitchenDesignerAssetValidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('passed', 'Passed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('detected_format', models.CharField(blank=True, max_length=20)),
                ('file_size_bytes', models.BigIntegerField(default=0)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('errors', models.JSONField(blank=True, default=list)),
                ('validated_at', models.DateTimeField(auto_now_add=True)),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kitchen_asset_validations', to=settings.AUTH_USER_MODEL)),
                ('designer_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_validations', to='planner.kitchendesignerproductprofile')),
            ],
            options={
                'ordering': ['-validated_at'],
            },
        ),
        migrations.CreateModel(
            name='KitchenProductionAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=120)),
                ('asset_type', models.CharField(choices=[('gcode', 'G-code'), ('cnc_program', 'CNC program'), ('toolpath', 'Toolpath'), ('setup_sheet', 'Setup sheet'), ('cut_list', 'Cut list'), ('manufacturing_pdf', 'Manufacturing PDF'), ('other', 'Other')], default='other', max_length=30)),
                ('file', models.FileField(upload_to=planner.models._production_asset_upload_path)),
                ('file_format', models.CharField(blank=True, max_length=30)),
                ('machine_profile', models.CharField(blank=True, max_length=120)),
                ('variant_key', models.CharField(blank=True, max_length=120)),
                ('version_label', models.CharField(blank=True, max_length=80)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('designer_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_assets', to='planner.kitchendesignerproductprofile')),
            ],
            options={
                'ordering': ['label', '-created_at'],
            },
        ),
    ]
