# Generated by Django 5.2.7 on 2026-03-06 15:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KitchenProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Untitled kitchen project', max_length=160)),
                ('slug', models.SlugField(blank=True, max_length=80, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('validating', 'Validating'), ('valid', 'Valid'), ('invalid', 'Invalid'), ('proceeding', 'Proceeding'), ('ordered', 'Ordered'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('estimated_price', models.FloatField(default=0)),
                ('share_token', models.CharField(blank=True, max_length=64, null=True)),
                ('share_mode', models.CharField(choices=[('private', 'Private'), ('view_link', 'View link')], default='private', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kitchen_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KitchenProjectVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_name', models.CharField(blank=True, max_length=120)),
                ('version_number', models.PositiveIntegerField()),
                ('scene_snapshot', models.JSONField(blank=True, default=dict)),
                ('price_snapshot', models.FloatField(default=0)),
                ('validation_summary', models.JSONField(blank=True, default=dict)),
                ('is_auto_snapshot', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kitchen_project_versions', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='planner.kitchenproject')),
                ('source_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_versions', to='planner.kitchenprojectversion')),
            ],
            options={
                'ordering': ['-version_number', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='kitchenproject',
            name='current_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='planner.kitchenprojectversion'),
        ),
        migrations.AddConstraint(
            model_name='kitchenprojectversion',
            constraint=models.UniqueConstraint(fields=('project', 'version_number'), name='unique_kitchen_project_version_number'),
        ),
    ]
