# Generated by Django 5.2.7 on 2026-03-06 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_kitchenproject_kitchenprojectversion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KitchenCartBundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('superseded', 'Superseded'), ('checked_out', 'Checked out')], default='active', max_length=20)),
                ('bundle_total', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_bundles', to='planner.kitchenproject')),
                ('project_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_bundles', to='planner.kitchenprojectversion')),
            ],
            options={
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KitchenValidationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('passed', 'Passed'), ('failed', 'Failed')], default='failed', max_length=20)),
                ('hard_issue_count', models.PositiveIntegerField(default=0)),
                ('soft_issue_count', models.PositiveIntegerField(default=0)),
                ('issues', models.JSONField(blank=True, default=list)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(auto_now=True)),
                ('project_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validation_runs', to='planner.kitchenprojectversion')),
            ],
            options={
                'ordering': ['-completed_at', '-started_at'],
            },
        ),
    ]
