# Generated by Django 5.2.7 on 2026-03-06 16:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_kitchencartbundle_kitchenvalidationrun'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KitchenProjectDuplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('rep_assist', 'Rep assist'), ('customer_copy', 'Customer copy'), ('variant', 'Variant'), ('other', 'Other')], default='customer_copy', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('duplicated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kitchen_project_duplications', to=settings.AUTH_USER_MODEL)),
                ('duplicated_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duplication_targets', to='planner.kitchenproject')),
                ('source_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duplication_sources', to='planner.kitchenproject')),
                ('source_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplication_sources', to='planner.kitchenprojectversion')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
