"""Add planner taxonomy fields to designer product profiles."""

# Generated by Django 5.2.7 on 2026-03-11 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0004_kitchenprojectduplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitchendesignerproductprofile',
            name='planner_group_category',
            field=models.CharField(blank=True, choices=[('base_cabinets', 'Base cabinets'), ('wall_cabinets', 'Wall cabinets'), ('high_cabinets', 'High cabinets')], max_length=40),
        ),
        migrations.AddField(
            model_name='kitchendesignerproductprofile',
            name='planner_leaf_category',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='kitchendesignerproductprofile',
            name='planner_root_category',
            field=models.CharField(blank=True, choices=[('cabinets', 'Cabinets'), ('appliances', 'Appliances'), ('dining', 'Dining'), ('kitchen_extras', 'Kitchen extras')], max_length=40),
        ),
    ]