# Generated by Django 5.1.7 on 2025-11-02 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='bonus',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='deductions',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='position',
        ),
    ]
