# Generated by Django 5.2.7 on 2025-11-08 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_employee_bonus_remove_employee_deductions_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
