"""Expand employee, attendance, and payroll models with active-state and worker-id support."""

# Generated by Django 5.2.7 on 2026-02-08 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_customer_profile_purchase_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='worker_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('final', 'Final')], default='draft', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('year', 'month', 'status'), name='unique_attendance_record_status')],
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecordEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(blank=True, max_length=120)),
                ('department', models.CharField(blank=True, max_length=120)),
                ('worker_id', models.CharField(blank=True, max_length=50)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.employee')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='core.attendancerecord')),
            ],
            options={
                'unique_together': {('record', 'worker_id')},
            },
        ),
        migrations.CreateModel(
            name='AttendanceShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.PositiveSmallIntegerField()),
                ('raw_logs', models.JSONField(blank=True, default=list)),
                ('morning_in', models.CharField(blank=True, max_length=20)),
                ('morning_out', models.CharField(blank=True, max_length=20)),
                ('afternoon_in', models.CharField(blank=True, max_length=20)),
                ('afternoon_out', models.CharField(blank=True, max_length=20)),
                ('morning_status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('missing', 'Missing')], default='missing', max_length=10)),
                ('afternoon_status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('missing', 'Missing')], default='missing', max_length=10)),
                ('record_employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='core.attendancerecordemployee')),
            ],
            options={
                'unique_together': {('record_employee', 'day')},
            },
        ),
    ]
