"""Add roster templates and employee roster assignments for schedule-aware attendance."""

# Generated by Django 5.2.7 on 2026-03-31 08:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_employee_is_active_employee_worker_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeRosterAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_start_date', models.DateField(default=django.utils.timezone.localdate)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['employee_id'],
            },
        ),
        migrations.CreateModel(
            name='RosterTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('cycle_length_weeks', models.PositiveSmallIntegerField(default=1)),
                ('schedule', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['name', 'id']},
        ),
        migrations.AlterField(
            model_name='employee',
            name='worker_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='attendancerecordemployee',
            unique_together={('record', 'worker_id', 'employee_name')},
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.UniqueConstraint(fields=('worker_id', 'name'), name='unique_employee_worker_name'),
        ),
        migrations.AddField(
            model_name='employeerosterassignment',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='roster_assignment', to='core.employee'),
        ),
        migrations.AddField(
            model_name='employeerosterassignment',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='core.rostertemplate'),
        ),
    ]
