"""Adjust attendance-shift status choices during payroll workflow refinement."""

# Generated by Django 5.2.7 on 2026-03-31 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_employeerosterassignment_rostertemplate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendanceshift',
            name='afternoon_status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('off', 'Off day'), ('missing', 'Missing')], default='missing', max_length=10),
        ),
        migrations.AlterField(
            model_name='attendanceshift',
            name='morning_status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('off', 'Off day'), ('missing', 'Missing')], default='missing', max_length=10),
        ),
    ]
