# Generated by Django 5.2.7 on 2026-04-02 02:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_attendanceshift_afternoon_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendanceshift',
            name='afternoon_status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('off', 'Off day'), ('missing', 'Missing'), ('approved_leave', 'Approved leave'), ('unapproved_leave', 'Unapproved leave')], default='missing', max_length=20),
        ),
        migrations.AlterField(
            model_name='attendanceshift',
            name='morning_status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('off', 'Off day'), ('missing', 'Missing'), ('approved_leave', 'Approved leave'), ('unapproved_leave', 'Unapproved leave')], default='missing', max_length=20),
        ),
        migrations.CreateModel(
            name='AttendanceOvertimeDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_date', models.DateField()),
                ('attendance_shift', models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon')], max_length=20)),
                ('roster_start_time', models.CharField(blank=True, max_length=20)),
                ('roster_end_time', models.CharField(blank=True, max_length=20)),
                ('actual_checkout_time', models.CharField(blank=True, max_length=20)),
                ('potential_ot_minutes', models.PositiveIntegerField(default=0)),
                ('approved_ot_minutes', models.PositiveIntegerField(default=0)),
                ('denied_ot_minutes', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied'), ('partially_approved', 'Partially approved')], default='pending', max_length=20)),
                ('decision_reason', models.TextField(blank=True)),
                ('narrowed_decision_enabled', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overtime_decisions', to='core.employee')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_attendance_overtime_decisions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['attendance_date', 'employee_id', 'attendance_shift'],
                'unique_together': {('employee', 'attendance_date', 'attendance_shift')},
            },
        ),
        migrations.CreateModel(
            name='AttendanceOvertimeDecisionSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment_start_time', models.CharField(max_length=20)),
                ('segment_end_time', models.CharField(max_length=20)),
                ('segment_minutes', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('denied', 'Denied')], max_length=20)),
                ('note', models.TextField(blank=True)),
                ('overtime_decision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='core.attendanceovertimedecision')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeLeaveRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_date', models.DateField()),
                ('leave_start_time', models.CharField(blank=True, max_length=20)),
                ('leave_end_time', models.CharField(blank=True, max_length=20)),
                ('submission_status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('recorded_unapproved', 'Recorded unapproved')], default='submitted', max_length=20)),
                ('duration_unit', models.CharField(choices=[('full_day', 'Full day'), ('half_day', 'Half day'), ('hour', 'Hour'), ('custom_minutes', 'Custom minutes')], default='full_day', max_length=20)),
                ('duration_value', models.FloatField(default=0)),
                ('leave_minutes', models.PositiveIntegerField(default=0)),
                ('employee_reason', models.TextField(blank=True)),
                ('manager_note', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('decision_at', models.DateTimeField(blank=True, null=True)),
                ('linked_attendance_shift', models.CharField(blank=True, choices=[('', 'Unlinked'), ('morning', 'Morning'), ('afternoon', 'Afternoon')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('decision_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_employee_leave_records', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_records', to='core.employee')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_employee_leave_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['leave_date', 'employee_id', 'id'],
            },
        ),
    ]
