"""Expand attendance and payroll summaries with early-departure and related totals."""

# Generated by Django 5.2.7 on 2026-04-30 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_payrollpolicy_overtime_grace_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancemonthlysummary',
            name='early_departure_minutes_total',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attendancemonthlysummary',
            name='time_bank_minutes_total',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payrollmonthlysummary',
            name='total_approved_ot_offset_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payrollmonthlysummary',
            name='total_early_departure_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payrollmonthlysummary',
            name='total_payable_ot_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payrollmonthlysummary',
            name='total_time_bank_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payrollrunemployee',
            name='approved_ot_offset_minutes_total',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payrollrunemployee',
            name='closing_time_bank_minutes_total',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payrollrunemployee',
            name='deductible_minutes_total',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payrollrunemployee',
            name='early_departure_minutes_total',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payrollrunemployee',
            name='opening_time_bank_minutes_total',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payrollrunemployee',
            name='payable_ot_minutes_total',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payrollrunemployee',
            name='settled_time_bank_minutes_total',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payrollrunemployee',
            name='time_bank_minutes_total',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='AttendanceTimeBankEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('early_departure_debt', 'Early departure debt'), ('ot_settlement', 'Approved OT settlement')], max_length=40)),
                ('entry_date', models.DateField()),
                ('attendance_shift', models.CharField(blank=True, choices=[('morning', 'Morning'), ('afternoon', 'Afternoon')], max_length=20)),
                ('minutes_delta', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_time_bank_entries', to='core.employee')),
                ('payroll_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='time_bank_entries', to='core.payrollrun')),
            ],
            options={
                'ordering': ['entry_date', 'employee_id', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeAttendanceWorkRuleProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_rule', models.CharField(choices=[('standard', 'Standard attendance rule'), ('driver_time_bank', 'Driver attendance rule with time bank')], default='standard', max_length=40)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_work_rule_profiles', to='core.employee')),
            ],
            options={
                'ordering': ['employee_id', '-effective_from', '-id'],
            },
        ),
    ]
